name: Cypress Tests + Relatório

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:           # ← ADICIONAR ESTE BLOCO
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🧪 Rodar testes Cypress
        run: npm run cy:report
        continue-on-error: true

      - name: 🛠️ Compilar HTML do Relatório
        run: |
          npx mochawesome-merge "cypress/reports/.jsons/*.json" -o merged-report.json
          npx marge merged-report.json --reportDir cypress/reports
        continue-on-error: true

      - name: 📊 Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports
          destination_dir: relatorio

